# Generated by Django 2.0.7 on 2018-10-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_favoriteitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteitem',
            old_name='Item',
            new_name='item',
        ),
    ]
